### ISSUE TITLE
Västtrafik API

### ISSUE THREAD

**Issue by XP64** [Kirens/DAT256#55]
Undersöka hur biljettverifiering kan ske genom API. Finns en vettig API skapas en ny uppgift.

# Subtasks
* [ ] Undersöka västtrafiks APIer
* [ ] Vid behov kontakta västtrafik för att undersöka ytterligare möjligheter

**Comment by elinsilver** [comment]
Under möte med västtrafik diskuterades detta och det framkom att det inte finns lätta sätt att verifiera biljetter. Använder istället fejk-biljetter
