### ISSUE TITLE
Not the same question twice

### ISSUE THREAD

**Issue by elinsilver** [Kirens/DAT256#59]
**As a** user **I want to** answer different question every time **since** the user don't want to answer the same question multiple times

# Acceptance Criteria
* [x] Not possible for a user to answer the same question more than one time

# View comments, needs more specification

**Comment by stenspanar** [comment]
Tänker att den här user storyn behöver specificeras om vi vill 
a. det inte ska vara samma fråga under samma spel
eller
b.. det inte ska kunna komma tillbaka samma fråga till samma person någonsin
