### ISSUE TITLE
Don't reorder alternatives when correct answer is shown

### ISSUE THREAD

**Issue by DanielWillim** [Kirens/DAT256#73]
**As a** user **I want to** not be confused when answering quesitons **since** thats no fun

# Acceptance Criteria
* [ ] When a answer is pressed it should only color the alternatives not reorder them
* [ ] The UI:s of correct answer screen and question screen should be similar enougth that the transition is smooth

# Definition of done
* [ ] Code compiles

**Comment by Kirens** [comment]
This seems to be fixed
